source "%val{config}/plugins/plug.kak/rc/plug.kak"

## Plugins

plug "delapouite/kakoune-text-objects"
plug "h-youhei/kakoune-surround"
plug 'delapouite/kakoune-buffers'
plug 'kakoune-editor/kakoune-extra-filetypes' # slow!
plug "andreyorst/smarttab.kak"
plug "loovjo/ad-hoc-org-mode"
plug "loovjo/quick-highlight"
plug "Delapouite/kakoune-mirror"
plug "caksoylar/kakoune-focus"

plug "krobelus/kak-lsp" branch "lightbulbs-for-code-actions" do %{
    cargo install --locked --force --path .
}

set global lsp_cmd "kak-lsp -s %val{session} --config ~/.config/kak/kak-lsp.toml"
set global lsp_cmd "%opt{lsp_cmd} -vvv --log /tmp/kak-lsp.log"

plug "ul/kak-tree" do %{
    cargo install --locked --force --path . --features "c cpp css haskell html javascript json python rust"
}

plug 'stoand/kakoune-idris'

### Configs

# colorscheme solarized-dark
colorscheme gruvbox-dark

# highlight whitespace at end of line
add-highlighter global/ regex '^.*[^ ]( +)$' 1:black,red
add-highlighter global/ number-lines -relative -hlcursor


hook global WinSetOption .* %{
    remove-highlighter global/show-ws
    add-highlighter global/show-ws show-whitespaces -tabpad ' '

    face global Whitespace rgb:3c3836+f
    face global comment rgb:665c54+f
}

add-highlighter global/ show-matching
hook global BufCreate .* %{
    expandtab
}

set global tabstop 4

## == keybinds ==

map global normal '=' ':format-buffer<ret>'

# tabs
map global insert '<tab>' '<a-;><a-gt>'
map global insert '<s-tab>' '<a-;><a-lt>'

define-command W w


# emulate alt-keybinds with "ä"
# dosen't work that well :(
source "~/Documents/configs/kak/alt-proxy.kak"

# Commenting
map global normal '#' ':comment-line<ret>'
map global user '#' ':comment-block<ret>' -docstring 'Block comment'

# Clipboard commands
map global normal '<a-y>' '|pbcopy<ret>u:echo "Copied text to clipboard"<ret>'
map global alt-proxy 'y' '|pbcopy<ret>u:echo "Copied text to clipboard"<ret>'
map global normal '<c-v>' '!pbpaste<ret>'

# Buffer user mode
map global user 'b' ':enter-user-mode buffers<ret>' -docstring 'buffer mode'
map global user 'B' ':enter-user-mode -lock buffers<ret>' -docstring 'buffer mode (lock)'


## == plugin configuration ==

## View
map global view 'f' '<esc>:focus-toggle<ret>vv' -docstring "Toggle focus mode"
map global view 'F' '<esc>:focus-clear<ret>' -docstring "Disable focus mode"

# Idris user mode
map global user 'i' ':enter-user-mode idris-ide<ret>' -docstring 'idris mode'
map global user 'I' ':enter-user-mode -lock idris-ide<ret>' -docstring 'idris mode (lock)'

# Custom function surround
define-command -hidden surround-function %{
    prompt 'function: ' %{
        execute-keys "<a-:><a-;>Z;ha%val{text}(<esc><a-;>L<a-z>ua)<esc>"
    }
}
define-command -hidden surround-tag %{
    prompt 'tag: ' %{
        execute-keys "<a-:><a-;>Z;ha<lt>%val{text}<gt><esc><a-;>L<a-z>ua<lt>/%val{text}<gt><esc>"
    }
}
define-command -hidden surround-Tag %{
    prompt 'tag: ' %{
        execute-keys "<a-x>Z<a-:><a-;>gih<a-h>yz<gt><a-x>ZO<c-r>""<lt>%val{text}<gt><esc>zo<c-r>""<lt>%val{text}<gt><esc>z"
    }
}
define-command -hidden surround-ins %{
    prompt 'prefix: ' %{
        execute-keys "<a-:><a-;>Z;ha%val{text}<esc><a-;>L<a-z>u"
    }
}
map global mirror 'f' ':surround-function<ret>' -docstring 'function'
map global mirror 't' ':surround-tag<ret>' -docstring 'function'
map global mirror 'T' ':surround-Tag<ret>' -docstring 'function'
map global mirror 'i' ':surround-ins<ret>' -docstring 'function'

map global normal ö ':enter-user-mode mirror<ret>' -docstring 'mirror mode'
map global normal Ö ':enter-user-mode -lock mirror<ret>' -docstring 'mirror mode (lock)'

# LSP stuff
map global normal 'Å' ':lsp-enable<ret>' -docstring 'Enable LSP'
map global normal 'å' ':enter-user-mode lsp<ret>' -docstring 'LSP mode'
map global lsp 'R' ':lsp-rename-prompt<ret>' -docstring 'Rename symbol'

define-command lsp-clear-references %{
    set-option window lsp_references # empty
}
map global lsp '"' ':lsp-clear-references<ret>' -docstring "Clear references"

face global Reference white,rgb:550055
face global ReferenceBind white,rgb:552200

map global insert '<c-s>' '<a-;>:enter-user-mode lsp<ret>s'

map global user '&' ':qhl-word<ret>' -docstring "Highlight current word"
map global user '"' ':unqhl<ret>' -docstring "Remove highlight"

## == Colors ==

define-command update-cursor-style %{
    evaluate-commands %sh{
        if [ $(echo "$kak_selection" | wc -c) -eq 2 ] ; then
            echo 'face buffer PrimaryCursor white,+uiF'
        else
            echo 'face buffer PrimaryCursor white,rgb:b05fde+uiF'
        fi
    }
}

hook global NormalKey .* %{
    update-cursor-style
}

hook global WinCreate .* %{
    update-cursor-style
}

face global PrimaryCursorEol PrimaryCursor
face global SecondaryCursorEol SecondaryCursor

face global operator blue
face global type rgb:aa66ee+b

face global MenuBackground rgb:eecc44+i
face global MenuForeground blue+bi
face global Information rgb:44ccee+b

face global MatchingChar ,rgb:665c54+bF

source ~/.config/kak/custom-highlighting/ats.kak
source ~/.config/kak/custom-highlighting/unison.kak
source ~/.config/kak/custom-highlighting/bfpp.kak
source ~/.config/kak/custom-highlighting/j.kak
source ~/.config/kak/custom-highlighting/bqn.kak

## Filetype formatting

hook global BufSetOption filetype=rust %{
    set-option buffer formatcmd 'rustfmt'

    hook buffer -group rust-inlay-hints BufReload .* rust-analyzer-inlay-hints
    hook buffer -group rust-inlay-hints NormalIdle .* rust-analyzer-inlay-hints
}

hook global WinSetOption filetype=python %{
    set-option window formatcmd 'black -q  -'
}

set-option global ui_options terminal_assistant=cat # 😺

