source "%val{config}/plugins/plug.kak/rc/plug.kak"

## Plugins

plug "delapouite/kakoune-text-objects"
plug "h-youhei/kakoune-surround"
plug 'delapouite/kakoune-buffers'
plug 'kakoune-editor/kakoune-extra-filetypes' # slow!
plug "andreyorst/smarttab.kak"
plug "loovjo/ad-hoc-org-mode"
plug "Delapouite/kakoune-mirror"

# plug "andreyorst/powerline.kak" config %{
#     powerline-start
# }
# hook global WinCreate ".*" %{
#     powerline-theme red-phoenix
# }

# slow!
plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
}


set global lsp_cmd "kak-lsp -s %val{session} --config ~/.config/kak/kak-lsp.toml"
set global lsp_cmd "%opt{lsp_cmd} -vvv --log /tmp/kak-lsp.log"


plug "ul/kak-tree" do %{
    cargo install --locked --force --path . --features "c cpp css haskell html javascript json python rust"
}

plug 'stoand/kakoune-idris'

### Configs

## Long lines highlighting
add-highlighter global/ number-lines -relative

# add-highlighter global/ regex '^[^\n]{100}([^\n]+)$' 1:black,rgb:880000
add-highlighter global/ regex '^.*[^ ]( +)$' 1:black,red

hook global WinSetOption .* %{
    remove-highlighter global/show-ws
    add-highlighter global/show-ws show-whitespaces
    face global Whitespace black
}

add-highlighter global/ show-matching
face global MatchingChar bold

# set-option global autowrap_column 100

# hook global InsertBegin .* autowrap-enable

hook global BufCreate .* %{
    expandtab
}

set global tabstop 4

define-command join %{
    prompt 'join on: ' %{
        execute-keys "<a-p><a-space>a%val{text}<esc>;"
    }
}

map global user 'j' ':join<ret>' -docstring ':join'

map global normal '=' ':format-buffer<ret>'

## Quick keybinds

# tabs
map global insert '<tab>' '<a-;><a-gt>'
map global insert '<s-tab>' '<a-;><a-lt>'

source "~/Documents/configs/kak/alt-proxy.kak"

map global insert '<c-a>' '<esc>i'
map global insert '<c-e>' '<esc>a'

map global insert '<c-o>' '<a-;>'
map global insert '<c-u>' '<esc>'
map global insert '<c-b>' '<a-;>:enter-user-mode buffers<ret>'

map global insert '<s-left>' '<a-;>H'
map global insert '<s-right>' '<a-;>L'
map global insert '<s-up>' '<a-;>K'
map global insert '<s-down>' '<a-;>J'

map global normal '<c-e>' 'vj'
map global normal '<c-y>' 'vk'

## Prompt maps for regex

map global prompt '<a-b>' '\b'
map global prompt '<a-w>' '\w'
map global prompt '<a-d>' '\d'
map global prompt '<a-s>' '\s'
map global prompt '<a-n>' '\n'
map global prompt '<a-q>' '\Q'

map global prompt '<a-B>' '\B'
map global prompt '<a-W>' '\W'
map global prompt '<a-D>' '\D'
map global prompt '<a-S>' '\S'

## Buffer user mode

map global user 'b' ':enter-user-mode buffers<ret>' -docstring 'buffer mode'
map global user 'B' ':enter-user-mode -lock buffers<ret>' -docstring 'buffer mode (lock)'

## Idris user mode

map global user 'i' ':enter-user-mode idris-ide<ret>' -docstring 'idris mode'
map global user 'I' ':enter-user-mode -lock idris-ide<ret>' -docstring 'idris mode (lock)'

## Custom function surround
define-command -hidden surround-function %{
    prompt 'function: ' %{
        execute-keys "<a-:><a-;>Z;ha%val{text}(<esc><a-;>L<a-z>ua)<esc>"
    }
}
define-command -hidden surround-tag %{
    prompt 'tag: ' %{
        execute-keys "<a-:><a-;>Z;ha<lt>%val{text}<gt><esc><a-;>L<a-z>ua<lt>/%val{text}<gt><esc>"
    }
}
define-command -hidden surround-Tag %{
    prompt 'tag: ' %{
        execute-keys "<a-x>Z<a-:><a-;>gih<a-h>yz<gt><a-x>ZO<c-r>""<lt>%val{text}<gt><esc>zo<c-r>""<lt>%val{text}<gt><esc>z"
    }
}
define-command -hidden surround-ins %{
    prompt 'prefix: ' %{
        execute-keys "<a-:><a-;>Z;ha%val{text}<esc><a-;>L<a-z>u"
    }
}
map global mirror 'f' ':surround-function<ret>' -docstring 'function'
map global mirror 't' ':surround-tag<ret>' -docstring 'function'
map global mirror 'T' ':surround-Tag<ret>' -docstring 'function'
map global mirror 'i' ':surround-ins<ret>' -docstring 'function'

map global normal ö ':enter-user-mode mirror<ret>' -docstring 'mirror mode'
map global normal Ö ':enter-user-mode -lock mirror<ret>' -docstring 'mirror mode (lock)'
map global user "'" ':enter-user-mode surround<ret>'


## Commenting
map global normal '#' ':comment-line<ret>'
map global user '#' ':comment-block<ret>' -docstring 'Block comment'

## Search for token
map global normal '<a-S>' 's\b\b<left><left>'
map global alt-proxy 'S' 's\b\b<left><left>'

## Clipboard commands
map global normal '<a-y>' '|pbcopy<ret>u:echo "Copied text to clipboard"<ret>'
map global alt-proxy 'y' '|pbcopy<ret>u:echo "Copied text to clipboard"<ret>'
map global normal '<c-v>' '!pbpaste<ret>'

## LSP stuff

# map global user 'l' ':enter-user-mode lsp<ret>' -docstring 'LSP mode'
# map global lsp 'l' ':lsp-enable-window<ret>' -docstring 'Enable LSP'
# map global user 'L' ':lsp-enable-window<ret>' -docstring 'Enable LSP'
map global normal 'å' ':enter-user-mode lsp<ret>'
map global normal 'Å' ':lsp-enable-window<ret>'
map global lsp 'R' ':lsp-rename-prompt<ret>' -docstring 'Rename symbol'

map global insert '<c-s>' '<a-;>:enter-user-mode lsp<ret>s'

define-command -params 0 wrap %{exec '<a-x>H|tw 100<ret>'}

define-command -params 1 goto-line %{select "%arg{1}.1,%arg{1}.1"}
alias global g goto-line

define-command W w


## Colors


face global SecondaryCursor    black,rgb:6fdce8
face global SecondarySelection white,rgb:064f57

face global PrimarySelection white,rgb:590987

define-command update-cursor-style %{
    evaluate-commands %sh{
        if [ $(echo "$kak_selection" | wc -c) -eq 2 ] ; then
            echo 'face buffer PrimaryCursor white,+ui'
        else
            echo 'face buffer PrimaryCursor white,rgb:b05fde+ui'
        fi
    }
}

hook global NormalKey .* %{
    update-cursor-style
}

hook global WinCreate .* %{
    update-cursor-style
}

face global PrimaryCursorEol PrimaryCursor
face global SecondaryCursorEol SecondaryCursor

# face global PrimaryCursor      black,rgb:fcd267+ui
# face global PrimaryCursorEol   black,rgb:fcd267+ui
# face global SecondaryCursor    black,rgb:d8aa61
# face global SecondaryCursorEol black,rgb:d8aa61

# face global PrimarySelection   black,rgb:ffb700+i
# face global SecondarySelection black,rgb:ad9761


face global operator blue
face global type rgb:aa66ee+b

face global MenuBackground rgb:eecc44+i
face global MenuForeground blue+bi
face global Information rgb:44ccee+b

source ~/.config/kak/custom-highlighting/ats.kak
source ~/.config/kak/custom-highlighting/unison.kak
source ~/.config/kak/custom-highlighting/bfpp.kak

## Filetype formatting

hook global BufSetOption filetype=rust %{
    set-option buffer formatcmd 'rustfmt'

    hook buffer -group rust-inlay-hints BufReload .* rust-analyzer-inlay-hints
    hook buffer -group rust-inlay-hints NormalIdle .* rust-analyzer-inlay-hints
    # hook window -group rust-inlay-hints InsertIdle .* rust-analyzer-inlay-hints
}

hook global WinSetOption filetype=python %{
    set-option window formatcmd 'black -q  -'
}
